#!/bin/sh /etc/rc.common

NAME=S80ganesha
PROG=/opt/bin/ganesha.nfsd
START=80
STOP=90

start() {
        LD_LIBRARY_PATH=/usr/lib:/opt/lib service_start $PROG
}
 
stop() {
        LD_LIBRARY_PATH=/usr/lib:/opt/lib service_stop $PROG
}

restart() {
        stop
        sleep 2
        start
}
